### ISSUE TITLE
Move heading variables into `_settings.defaults.scss`.

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/base.headings#4]
Now that there is [trumps.headings](https://github.com/inuitcss/trumps.headings) module, variables for headings should be global, therefore in `settings.defaults`.

**Comment by csshugs** [comment]
You have to keep in mind here: what if you don't integrate [base.headings](https://github.com/inuitcss/base.headings) and [trumps.headings](https://github.com/inuitcss/trumps.headings) in your project? `settings.default` will then contain these useless variables. 
I think it makes sense as it is now, because if you want to use [trumps.headings](https://github.com/inuitcss/trumps.headings), [base.headings](https://github.com/inuitcss/base.headings) is downloaded anyway (with bower), so the variables are then available.

**Comment by csshugs** [comment]
...similar to [trumps.spacing](https://github.com/inuitcss/trumps.spacing) and [trumps.spacing-responsive](https://github.com/inuitcss/trumps.spacing-responsive). If you want to use [trumps.spacing-responsive](https://github.com/inuitcss/trumps.spacing-responsive), [trumps.spacing](https://github.com/inuitcss/trumps.spacing) gets downloaded automatically by bower and the `$inuit-margin` and `$inuit-padding` variables are stored just in [trumps.spacing](https://github.com/inuitcss/trumps.spacing).

**Comment by nenadjelovac** [comment]
@csshugs you are missing one major thing here:

**You need to include those files/dependencies in your main scss file to have access to their variables.**

So if you need heading variables but you don't want `h1` - `h6` to have default style, then no luck for you.

> settings.default will then contain these useless variables

I see no harm done there. It's better to have unused variables than css that you don't need (or need to override). Also, headings look like [high-level base settings](https://github.com/inuitcss/settings.defaults/blob/master/_settings.defaults.scss#L17) to me. I might be wrong though, so let's see what @csswizardry has to say.

Btw, the examples you posted about spacings is different because it is trumps layer, and therefore all classes, where base layer are unclassed html elements. And responsive is extension of default state, so you still need to include both in your main scss file.

**Comment by csshugs** [comment]
> **You need to include those files/dependencies in your main scss file to have access to their variables.**
> 
> So if you need heading variables but you don't want h1 - h6 to have default style, then no luck for you.

To be honest, I don't get it. You want to use `.alpha` - `.zeta` without declaring the `$inuit-heading-size-` variables to the `h1` - `h6` elements? Am I getting you right? 

But isn't the idea behind `.alpha`, `.beta` etc. to be the equivalents of `h1` - `h6`? Then they should have the same font-sizes which leads me to the following use cases:
1. I don't want to use anything (browser default font-sizes for the headings), so none of the headings-modules get included.
2. I want to declare custom font-sizes for the headings, so `base.headings` gets included in my main scss file.
3. I want to have the ability for doing this (both modules get included):

``` html
<h3 class="alpha">Heading</h3>
```

For me, transplanting the headings variables into `settings.default` breaks the modularity (because of unused variables in case, none of the headings is imported).

**Comment by nenadjelovac** [comment]
> But isn't the idea behind .alpha, .beta etc. to be the equivalents of h1 - h6?

Yes, it is, but they are not the same. For example, you can do:

```
<dt class="alpha">Definition term that is styled like a heading</dt>
```

So this is utility class that you can apply to whatever you want, not just `h1` - `h6`. 

> To be honest, I don't get it. You want to use .alpha - .zeta without declaring the $inuit-heading-size- variables to the h1 - h6 elements? Am I getting you right?

It would be good to have that ability, and that would be more modular than it is now. With heading variables in `settings.defaults` you could have above example and yet `h1` - `h6` tags would have no style if you do not include `base.headings`. Hope this makes it clearer.

> For me, transplanting the headings variables into settings.default breaks the modularity (because of unused variables in case, none of the headings is imported).

I wouldn't agree it breaks modularity because `settings.defaults` (also functions and mixins) are only modules "[that are required for using any of the rest of the framework](https://github.com/inuitcss/settings.defaults/blob/master/README.md)". And as I said before, headings look like high-level base settings to me.

Also, with everything I wrote, all of your use cases from previous comments would be possible.

**Comment by csshugs** [comment]
Ok, I get it. 
But in my opinion don't declaring a font-size to `h1` - `h6` (thus letting browser default styles apply) don't makes sense if we want to use `.alpha` etc. 
I think we both agree that there will probably never be a website without any headings. So let's say we have the browser default styles applied to our headings (h1 is then 32px (and by the way not in the rem-unit)). Then we have an element which we want to be displayed in that font-size. Let's take your example:

``` html
<dt class="alpha">Definition term that is styled like a heading</dt>
```

So we'd do: 

``` scss
$inuit-heading-size-1:  32px;
```

Later on we need to alter the size of `.alpha`, so we'd do:

``` scss
$inuit-heading-size-1:  40px;
```

Our Element is now in a fine font-size, but it isn't actually `.alpha` anymore, because its font-size is deviating from `h1` (rather something like `.mega` etc).

What I mean with all this is: The headings get a font-size anyway (at least the browser default). So why not manage `h1` - `h6` and `.alpha` - `.zeta` together under one roof. You get the rem unit based font-size with pixel fallback and `h1` - `h6` and `.alpha` - `.zeta` are always equivalent to eachother.

I agree that these variables are high-level settings, but having those always available even if none of the headings modules is included is a overhead in the codebase to me and may as well lead to misconceptions for other developers thinking: "Why on earth doesn't this variable affect the font-size of my `h1`?". 
I am really the opinion that there is no use case for including `trumps.headings` without `base.headings` and therefore the variables could stay in `base.headings`. But I would like to hear other opinions than mine and @nenadjelovac. @anselmh @csswizardry @florianbouvot

**Comment by nenadjelovac** [comment]
wow, I thought this was a no-brainer issue, but it got so interesting :) 

@csshugs you raised a really really good question with setting the variable in codebase twice. I didn't think about that because we (at work) have `_settings.inuit.scss` where we set all of our inuit variables for the project (and **don't** reset them afterwards) [as per this](https://github.com/csswizardry/csswizardry.github.com/issues/48#issuecomment-49019705) and [last paragraphs from here](https://github.com/inuitcss/getting-started#modifying-inuitcss). That way we enforce that all variables are set only **once**, are set **at one place** and don't get accidentally overridden. 

So @csswizardry, what @csshugs realized is that now that we have `base.headings` and `trumps.headings`, you could do something like this:

```
$inuit-heading-size-1: 22px;
@import "bower_components/inuit-headings/base.headings";

$inuit-heading-size-1: 42px;
@import "bower_components/inuit-headings-trumps/trumps.headings";
```

thus creating deviation between unclassed headings and classed headings.

<p class="sassmeister" data-gist-id="435ee6c02c9e39f8d627" data-height="480" data-theme="tomorrow"><a href="http://sassmeister.com/gist/435ee6c02c9e39f8d627">Check this gist on SassMeister.</a></p><script src="http://cdn.sassmeister.com/js/embed.js" async></script>

@csshugs 

> I am really the opinion that there is no use case for including trumps.headings without base.headings and therefore the variables could stay in base.headings.

Even if it stays the way it is now, you can have this:

> Our Element is now in a fine font-size, but it isn't actually .alpha anymore, because its font-size is deviating from h1 (rather something like .mega etc).

Please check SassMeister link I posted above.

Edit:

> But I would like to hear other opinions than mine and @nenadjelovac. @anselmh @csswizardry @florianbouvot

Me too. Ping guys ;)

Edit2:

Actually, this might come as a feature, but then there should be variables in `trumps.headings` that default to variables from `base.settings`. Eg:

```
$inuit-heading-trumps-size-1: $inuit-heading-size-1 !default;
```

**Comment by csshugs** [comment]
> So @csswizardry, what @csshugs realized is that now that we have base.headings and trumps.headings, you could do something like this:
> 
> ```
> $inuit-heading-size-1: 22px;
> @import "bower_components/inuit-headings/base.headings";
> 
> $inuit-heading-size-1: 42px;
> @import "bower_components/inuit-headings-trumps/trumps.headings";
> ```

@nenadjelovac Oh my god, I actually didn't had that in mind at all! That _is_ quite interesting :-)
You're right: It doesn't matter which way we go, something like this will always be possible, but nevertheless:

> Our Element is now in a fine font-size, but it isn't actually .alpha anymore, because its font-size is deviating from h1 (rather something like .mega etc).

In the example above, it isn't an equivalent to `h1` anymore (considering the font-size), which is actually the purpose, so I would disadvise overriding the variable as above (although it is possible).

In this case it becomes obvious to me that overriding all variables in seperate partials (as you do it) is in this case an advantage. I do it as suggested [here](https://github.com/inuitcss/getting-started#modifying-inuitcss) directly in the main scss file. So yeah, not knowing that circumstance above could lead into setting the variable twice accidentally.

---

Aside from all that, I still think, the variables should kept away from `settings.defaults`. To be consequent, we'd even have to take these variables out of `settings.defaults`, too:

``` scss
$inuit-base-font-size:          16px !default;
$inuit-base-line-height:        24px !default;
$inuit-base-text-color:         #333 !default;
$inuit-base-background-color:   #fff !default;
```

...which is not possible, because `$inuit-base-line-height` is used to define `$inuit-base-spacing-unit` further down in `.settings.defaults`. 
And although these four variables are just used in `base.page`, they are as high-level as they could be used anywhere else in the codebase, so it is ok to keep them in there. 

But being able to use the heading variables for various elements (i.e. use the `.alpha`, `.beta` etc. classes) without declaring them to the headings `h1` - `h6` itself just makes no sense to me. I can't imagine a use case, where you want to tell an element to have the `$inuit-heading-size-1` font-size (e.g. 54px), but a `h1` has a deviating font-size of 32px.

Maybe I am too subjective and someone else ( @csswizardry @anselmh @florianbouvot ) can look at it in a sensible, objective way, which serves the framework best.

Edit:
Actually quite interesting we can make such mountains out of molehills :-)

**Comment by nenadjelovac** [comment]
> Actually quite interesting we can make such mountains out of molehills :-)

Indeed :) But we have found out quite an interesting situation here. 

 @csswizardry @anselmh @florianbouvot any thoughts?

**Comment by florianbouvot** [comment]
@nenadjelovac I'll take a look at this issue today ;)

**Comment by nenadjelovac** [comment]
Here is one more thing that makes me think these variables should be global. It's an excerpt from http://sass-guidelin.es/#variables section about what values are candidates to be a variable in the first place.

> A new variable should be created only when all of the following criteria are met:
> - the value is repeated at least twice;
> - the value is likely to be updated at least once;
> - all occurrences of the value are tied to the variable (i.e. not by coincidence).

So if we go the same route then if a variable is used in more than one layer (eg. base and trumps) it should probably be promoted to global variable (in `_settings.defaults.scss`).

**Comment by csshugs** [comment]
@nenadjelovac since this is pre-alpha and since we don't seem to have agreed on this topic (😜 ), wanna close this or continue the discussion right here?

**Comment by nenadjelovac** [comment]
@csshugs I think: let's close :P If it bumps up again we'll address it then ;)
